
CREATE TABLE `booking` (
  `id` int(11) NOT NULL,
  `user_id` varchar(50) NOT NULL,
  `pemakai` varchar(500) DEFAULT NULL,
  `institusi_id` int(11) DEFAULT NULL,
  `jenis_id` int(11) NOT NULL,
  `tanggal_mulai` date NOT NULL,
  `tanggal_akhir` date NOT NULL,
  `jam_mulai` time NOT NULL,
  `jam_akhir` time NOT NULL,
  `kegiatan` text DEFAULT NULL,
  `tempat_id` int(11) DEFAULT NULL,
  `trayek_id` int(11) DEFAULT NULL,
  `driver_id` int(11) DEFAULT NULL,
  `status_booking` int(11) NOT NULL DEFAULT 1,
  `keterangan_tambahan` text DEFAULT NULL,
  `harga` varchar(50) DEFAULT '0',
  `pesan` text DEFAULT NULL,
  `status_penilaian` varchar(20) NOT NULL DEFAULT 'belum dinilai',
  `created_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `updated_at` datetime DEFAULT NULL,
  `unit_kerja_nama` varchar(255) DEFAULT NULL,
  `file_proposal` varchar(255) DEFAULT NULL,
  `path` varchar(255) DEFAULT NULL,
  `keterangan_status` text DEFAULT NULL,
  `hp` varchar(255) DEFAULT NULL,
  `file_bukti_bayar` varchar(255) DEFAULT NULL,
  `path_bukti_bayar` varchar(255) DEFAULT NULL,
  `no_surat` varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;
